//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionReceipt
    {
        public int TransactionReceiptId { get; set; }
        public int TransactionId { get; set; }
        public byte[] ReceiptImage { get; set; }
        public string ContentType { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
